title = 'Simon "Tchiquito" Lambert'
theme = 'hugo-resume'
languageCode = "fr"
favicon = "favicon.ico"
baseURL = 'https://fennecdjay.github.io/tchiquito'
#baseURL = 'localhost:1313'
ignoreLogs = ['warning-goldmark-raw-html']

[params]
firstName = "Simon"
lastName = "Lambert"
phone =  '0635628108'
email = 'simonlambert@gmail.com'
showContatc = true
profileImage = "img/chiquito-bio.jpg"
#[[params.handles]]
sections = ["creations", "publications", "dates"]
